### ISSUE TITLE
How do I change editor content?

### ISSUE THREAD

**Issue by eguitarz** [froala/ember-froala#21]
I have a list of files, and when user selects on one of them will send value to editor's value.

```
{{froala-editor
    value=note.body
    placeholder="new note"
    key-up=(action "updateStatus")
  }}
```

But seems it won't reflect the new value even I changed `note.body`.

**Comment by artsmc** [comment]
Please use ember-froala-editor this current plugin will be depreciated soon
[ember-froala-editor](https://github.com/froala/ember-froala-editor)

**Comment by Panman82** [comment]
In addition, `placeholder` is actually a [Froala Editor option](https://www.froala.com/wysiwyg-editor/docs/options#placeholderText), and should be passed in as such (rather than defining it as a normal property).

In the new addon, your example would become:

```
{{froala-editor
    content=note.body
    options=(hash placeholderText="new note")
    on-keyup=(action "updateStatus")
}}
```

Although I'm not sure you'll need the `on-keyup` event action anymore since `content` is two-way-bound (via the `contentChanged` Froala Editor event).

**Comment by artsmc** [comment]
Yeah looks like inky is open source :
https://github.com/zurb/inky?files=1
That's the template language they created for zurb email.
So yup feel free to add that to the value proposition. I just need to build
some test.

**Comment by eguitarz** [comment]
^^^ Both are very helpful information, thanks!
