### ISSUE TITLE
What's the difference between this repo and ember-froala-editor?

### ISSUE THREAD

**Issue by danlourenco** [froala/ember-froala#22]
Is there some difference I'm not seeing? Should we be using one over the other?

**Comment by Panman82** [comment]
This repo (ember-froala) is the original ember addon for the Froala Editor, the ember-froala-editor repo is the "new" ember addon. Both will be maintained for a short time but eventually ember-froala will be depreciated in favor of ember-froala-editor. There are _two_ addons due to breaking differences in how you pass in options and event handlers/actions, etc.

**Comment by Panman82** [comment]
cc @artsmc plans on adding depreciation notices? I can add a few things in the coming weeks if you're busy.

**Comment by danlourenco** [comment]
Awesome--thanks! We're currently in the process of upgrading our Ember 1.12 app to the 2.4 LTS release, but it may be a few weeks before we get there.  I'll plan on sticking with this repo until that point; didn't seem like the newer version was working for me.

Cheers

**Comment by Panman82** [comment]
Correct, the `ember-froala-editor` addon requires Ember 1.13+ due to the new component lifecycle hooks.

Closing this issue for now, but let us know if you have further questions.
